### ISSUE TITLE
Restrict intellisense to files listed

### ISSUE THREAD

**Issue by sg-** [Microsoft/vscode-tips-and-tricks#24]
I'd like to reduce the noise intellisense is giving by creating a white list of files that it should index. Is this possible? I'd thought the below snippet would kill all indexing but it seems to still search the root project directory and all subdirectories with have a lot of nonsense for my particular project.

c_cpp_properties.json
```
{ 
    "configurations": [
        {
            "name": "Mac",
            "includePath": ["${workspaceRoot}/main.cpp"]
        }                
    ]
}
```
Any tips?

**Comment by waderyan** [comment]
Hmm.. This is going to be specific to your language. Not a great fit for this repo. Please open an issue in the language extension's repo.
