### ISSUE TITLE
How to switch to terminal?

### ISSUE THREAD

**Issue by ASalihov** [Microsoft/vscode-tips-and-tricks#27]
Is there a shortcut for switching from code editor to console terminal?

**Comment by forethoughtde** [comment]
There is a command called **workbench.action.terminal.focus**. You can define your own command. 

You can look at my own command below
```vsc
[{
    "key": "ctrl+1",
    "command": "workbench.action.terminal.focus",
    "when": "editorTextFocus"
}
]
```
The above command says that when the user is in the editor pressing CTRL+1 will take user to the terminal.

**Comment by ericblade** [comment]
hmm.  can think of a way to mod ctrl-` so that it will focus an existing terminal, or open one if there's not one? i'm not too keen on the behavior of it just opening new terminals all the time.

**Comment by ASalihov** [comment]
Thanks!
