### ISSUE TITLE
How to open a file from the explorer/sidebar?

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [Microsoft/vscode-tips-and-tricks#28]
Thanks for this great reference!

One can access the sidebar/explorer with `cmd`+`shift`+`e` on mac. But how to open a file from there or say, jump into that file?
`ctrl`+`enter` only opens it to the side.
just `enter` is used to rename the file…
Is that even possible?

**Comment by ThibaultJanBeyer** [comment]
hello?

**Comment by waderyan** [comment]
Sorry for the delay. This fell through the cracks on my end. 

AFAIK - what you are describing is not possible. Please look into making a feature request in the VS Code repo.
