### ISSUE TITLE
Go through past six months release notes

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-tips-and-tricks#31]

**Comment by forethoughtde** [comment]
Can I know what is the purpose behind going through past six-month release notes?

**Comment by waderyan** [comment]
Mine them for new tips and tricks that I have missed :)

**Comment by forethoughtde** [comment]
Okay. I'd like to do it; can you assign this to me?

**Comment by waderyan** [comment]
Sure!

**Comment by waderyan** [comment]
Hmm.. won't let me ... and I seem to have lost settings access. Please fork and open a PR. I manage this repo and I won't plan on picking this up.

**Comment by gregvanl** [comment]
Old issue.
