### ISSUE TITLE
ctrl+j Join Lines is not working

### ISSUE THREAD

**Issue by raksa** [Microsoft/vscode-tips-and-tricks#37]
**VS Code 1.8.1**
by default "ctrl+j Join Lines" is not working it just toggles enter terminal

**Comment by waderyan** [comment]
Strange. Its working for me. What OS are you on?

**Comment by raksa** [comment]
Windows 10

**Comment by happiness9721** [comment]
Same problem here.
OS: Windows 7
Version: VS Code 1.8.1 
And it's my default keybindings.json
![1484547179602](https://cloud.githubusercontent.com/assets/4532358/21972680/29b201cc-dbf6-11e6-97d6-949110d83b71.jpg)
Ctrl + j had been bound to togglePanel in default.

**Comment by nwservices** [comment]
"ctrl+j Merge Lines"   VS

"ctrl+j Join Lines"       SUBLIME
