### ISSUE TITLE
Language specific sub categories.

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode-tips-and-tricks#40]
It would be nice to have some language specific subcategories for sharing these types of Tips and Tricks that are more focused. They could be in their own Markdown files in a Languages folder or similar so they aren't cluttering the main markdown file.

**Comment by gregvanl** [comment]
Thank you for the suggestion. This README will be moving to vscode-docs to be with the main VS Code documentation. We could Tips and Tricks sections to the existing language topics (for example, Markdown, CSS, HTML).
