### ISSUE TITLE
Section about terminal (CLI tool) is not correct

### ISSUE THREAD

**Issue by stej** [Microsoft/vscode-tips-and-tricks#43]
I'm following 

> Open the command palette (F1) and type "shell command". Hit enter to execute "Shell Command: Install 'code' command in PATH".

When I type "shell command", there is no option. I see only PowerShell
![2017-03-22_12h21_14](https://cloud.githubusercontent.com/assets/253560/24195447/1615660e-0efa-11e7-98b0-81333eea36f6.png)

Is it needed to enable the shell somewhere? 

I'm on version 1.10.2

**Comment by Tyriar** [comment]
The shell command install is only necessary on macOS. @waderyan this can be closed off
