### ISSUE TITLE
Git diff in one view

### ISSUE THREAD

**Issue by ButuzGOL** [Microsoft/vscode-tips-and-tricks#44]
Have two question
1. Is there any way to see all diff in one view like in gh ?
2. Is there any way to set Inline view as default ?

**Comment by sushruth** [comment]
This setting should help :

```json
  // Controls if the diff editor shows the diff side by side or inline
  "diffEditor.renderSideBySide": true,
```

**Comment by evenfrost** [comment]
> Is there any way to see all diff in one view like in gh ?

Came here from Google search with this exact question. Does anyone know if this is possible either without extension or with one?
