### ISSUE TITLE
Is there a way to see file is modified in explorer?

### ISSUE THREAD

**Issue by arvenil** [Microsoft/vscode-tips-and-tricks#46]
I mostly use file explorer to navigate through files and in most IDEs there is visual indicator for files that are changed. So a combined view of "explorer" and "source control" views. This way I can quickly identify modified files in source code tree. The "show only modified files" aka "source control" view is really handy as you can see only modified files but I don't understand the lack of indicator in explorer.

It's done usually by marking such files with different color
![example](https://cloud.githubusercontent.com/assets/450355/24813266/b30e79d4-1bcd-11e7-8bd0-388967517535.png)

Is there a way to see file is modified in explorer?

**Comment by waderyan** [comment]
There isn't a way today. Please upvote the feature request. https://github.com/Microsoft/vscode/issues/178
