### ISSUE TITLE
File Structure using Minimap

### ISSUE THREAD

**Issue by bmargogne** [Microsoft/vscode-tips-and-tricks#47]
[This is an idea for a new feature, not an issue]

When coding in particularly long files, it would be nice to have some possibilities to have additional navigation possibilities using the minimap. For instance, if we could define a file tree structure, similar as a table of content for any typical ".doc" document, we could very quickly go the desired portion of code.

Here is what it could look like : http://hpics.li/06f785f

Some additional ideas :

1) "simple" file sections would be declared using keyword in full commented lines (not sure if this is feasable on all file type...) :
////// [Minimap.section : Name of the section] ////////////////////////////////////

2) Sections be highligthed in the minimap to ease identification. The full section name could appear using a rollover.

3) [+] or [-] icons next to sections in the minimap would allow expanding/collapsing minimap portion of codes. When fully collapsed, it would display a kind of "table of content" for the file.

4) with "structured" file sections, a user could even define nested parts in his file structure.
////// [Minimap.sectionH1 : { some file section name } ///////////////
////// [Minimap.sectionH2 : { some file subSection name } ///////////

I guess if these keywords are used in commentaries, they would not harm the code when used outside of VScode ?

**Comment by sushruth** [comment]
Maybe you should take this to the VSCode repo ?

**Comment by bmargogne** [comment]
That sounds like a smart move :) (... I thought both would be followed by the VS code team)

**Comment by waderyan** [comment]
Thanks for the feedback. Please move this feature request to the vscode repo.
