### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tips-and-tricks#53]
- reference keybindings
  - the screenshot is out of date, key bindings are now rendered nicer - done
![image](https://user-images.githubusercontent.com/172399/27738474-b585a852-5dab-11e7-8612-03d61e4506a5.png)  
- quick open
  - show the score based matching in the animated gif, e.g., type AB and it will match `AppBar.js``
![image](https://user-images.githubusercontent.com/172399/27738557-f0051eea-5dab-11e7-8a52-f6b207113c0e.png)
  - mention that you can quickly navigate to a previously opened file by pressing CTRL+P repeatedly - done
- Errors and Warnings
  - mention that you can filter warning or errors by typing "error" or "warning" - done
![image](https://user-images.githubusercontent.com/172399/27738609-1a82ea30-5dac-11e7-97ca-f16c9514f326.png)
- Change Language Mode
  - mention that you can persist a change using 'Configure Association For' - done
  - mention that you can re-arrange the editors using drag and drop or drop an editor to a new location. -done
![image](https://user-images.githubusercontent.com/172399/27738438-9db5f2b8-5dab-11e7-9ba0-91e2fc6230e8.png)
- Find by symbol
  - should be called "Go to Symbol in File" - done
  - mention that you can group the symbol by kinds by typing "@:" - done
![image](https://user-images.githubusercontent.com/172399/27738736-85244488-5dac-11e7-8b2a-3d94a8435043.png)
- ADD: Go to Symbol in Workspace - done
![image](https://user-images.githubusercontent.com/172399/27738796-befc243c-5dac-11e7-8afe-8cf315bdf242.png)
- Go to Definition
  - mention that you can go back to the previous positions using Go>Back  ALT-LEFT ARROW - done
  - ADD: go to definition by CTRL+CLICK - done
![image](https://user-images.githubusercontent.com/172399/27739106-c7b11276-5dad-11e7-954f-f1b8de3e423b.png)
- Debugger
  - mention the setting "debug.inlineValues": true, to show the variable inline - done
- Tasks
  - Tasks section is out of date and needs to be updated to the latest. - moved to vscode-docs

**Comment by bpasero** [comment]
* mention that the right hand side of a diff editor is actually editable
*
