### ISSUE TITLE
Opening a file with right cursor (->) in Quick Open

### ISSUE THREAD

**Issue by dyong0** [Microsoft/vscode-tips-and-tricks#54]
Hi, I quite often try to open multiple files on Quick Open. But it seems not supported. But I found another way to open multiple files. You can open file with right cursor without closing Quick Open.

Can you add this tip on this project? I looked for this for a year 😱

**Comment by jpokrzyk** [comment]
Ah awesome.

Yea I struggled with the opening multiple files with quick open as well.
