### ISSUE TITLE
How to remove the tabs bar?

### ISSUE THREAD

**Issue by WaqasIbrahim** [Microsoft/vscode-tips-and-tricks#62]
Hi, I have already disabled tabs but the tabs bar still shows up with file name on it even in full screen mode. Is there any way to hide this? Thanks

![screenshot from 2017-08-05 05 59 09](https://user-images.githubusercontent.com/12554146/28991881-9feaa222-79a8-11e7-93f7-e976dd23fbf6.png)

**Comment by gregvanl** [comment]
No, I don't believe so. The title bar is always shown for the open file. Turning off tabs just means you don't see a tab for each open file in the title bar.
