### ISSUE TITLE
Shorcut keyboard not working in WindowsOS

### ISSUE THREAD

**Issue by lepatlamass** [Microsoft/vscode-tips-and-tricks#65]
Hi since I updated my Vscode some shortcut are not more walking.

**Comment by gregvanl** [comment]
Hi @lepatlamass, Can you describe which keyboard shortcuts are no longer working? We can then investigate and determine if there are product issues or if the documentation needs to be updated. Thanks.

**Comment by lepatlamass** [comment]
Hi @gregvanl thanks let me list it
-add cursor above(Ctrl + Alt + Up Arrow)
- Add Cursor below ( Ctrl + Alt + Up Arrow)
- Ctrl + D adding next occurrence
those are the once that I frequently used which I find that is not working for me.
Thanks again.

**Comment by gregvanl** [comment]
I don't think either of these key bindings has changed. Ctrl+Alt+Up/Down can be captured by some video drivers, for example my Asus Zenbook uses that keyboard shortcut sequence to flip the display.
Have you recently changed computers?
Ctrl+D should select the next match to the work your cursor is on if there is one. Ctrl+D is for Linux and Windows, it would be Cmd+D on macOS.

**Comment by lepatlamass** [comment]
OK now understanding, yes i change my laptop, and since then when i used the Ctrl+Alt+Up/Down is instead my display which is interpreted.Will check it back thanks for the help

**Comment by gregvanl** [comment]
@lepatlamass Glad we've solved the mystery 👍
